### ISSUE TITLE
Tron node synchronization issue

### ISSUE THREAD

**Issue by dzmitrykliapkou** [tronprotocol/java-tron#4129]
### 1. What did you do?
I'm running two tron nodes in AWS. I used a snapshot of the third one to launch this two nodes. The old node is running well, but these new nodes stuck at the same block number.

#### System description:
- AWS c5.4xlarge instance with 16 vcpu and 32 GB RAM
- Tron node is running in a docker container. Additional 1.5TB SSD disk is mounted as a directory to this container
- Java-tron version - GreatVoyage-v4.4.0
- Docker-compose file:
```yaml
version: '3'
services:
  tron:
    build:
      context: /root/java-tron/
    container_name: java-tron
    restart: unless-stopped
    ports:
      - "8090:8090"
      - "8091:8091" 
      - "18888:18888"
      - "50051:50051"
    volumes:
      - /data/output-directory/:/java-tron/data
      - /data/main_net_config.conf:/java-tron/main_net_config.conf
    command:
      - "-d"
      - "/java-tron/data"
      - "-jvm"
      - "{-Xmx10g -Xms10g}"
      - "-c"
      - "/java-tron/main_net_config.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
```
- command.txt
```bash
[root@ip-10-2-0-73 ~]#  docker exec -it java-tron cat /java-tron/command.txt
./bin/FullNode -d /java-tron/data -jvm {-Xmx10g -Xms10g} -c /java-tron/main_net_config.conf
```

- config file:
[main_net_config.conf](https://github.com/tronprotocol/java-tron/files/7379517/main_net_config.txt)

### 2. What did you expect to see?
The nodes are catching up and finally end up synced

### 3. What did you see instead?
```bash
sh-4.2$ curl -s http://127.0.0.1:8090/wallet/getnowblock | jq '.block_header.raw_data.number'
34710453
```
Returns the same value

here are some logs from the node
[tron.log](https://github.com/tronprotocol/java-tron/files/7379415/tron.log)

I wonder if this is a kind of normal behavior and I just need to wait some time or there is a real problem with the systems
