### ISSUE TITLE
Run java-tron using OpenJDK

### ISSUE THREAD

**Issue by air3ijai** [tronprotocol/java-tron#4133]
### 1. What did you do?
For now are running java-tron using OpenJDK installed on Ubuntu. It seems that it works fine, despite the mentioning on [How to Build](https://github.com/tronprotocol/java-tron/blob/develop/build.md):
```
On Linux Ubuntu system (e.g. Ubuntu 16.04.4 LTS), ensure that the machine has Oracle JDK 8, instead of having Open JDK 8 in the system. If you are building the source code by using Open JDK 8, you will get Build Failed result.
```
Or it is related only for the builds and we can run compiled jar using OpenJDK?

### 2. What did you expect to see?
We want to be able run java-tron using OpenJDK and have an official support for this.

### 3. What did you see instead?
For now we are run java-tron using OpenJDK.

As Oracle no longer releasing updates for long-term support (LTS) Java releases under a permissive license, there is a lot of other [OpenJDK](https://en.wikipedia.org/wiki/OpenJDK). 
For example we can very easy run java-tron using Docker and pre-compiled OpenJDK image:
```yml
version: '3'
services:
  tron:
    container_name: java-tron
    image: amazoncorretto:8
    network_mode: bridge
    restart: unless-stopped
    working_dir: /java-tron
    command: java -Xmx25g -XX:+UseConcMarkSweepGC -jar FullNode-4.3.0.jar -d data -c main_net_config.conf
    ports:
      - "8090:8090"        # HTTP API
      - "8091:8091"        # HTTP API Solidity
      - "18888:18888"      # P2P network TCP
      - "18888:18888/udp"  # P2P network UDP
      - "50051:50051"      # gRPC
    volumes:
      - /data:/java-tron
```

Thank you!
