### ISSUE TITLE
Docker Event subscribe no messages

### ISSUE THREAD

**Issue by iBugCode** [tronprotocol/java-tron#5980]
Lite FullNode

``` yml
# docker-compose.yml
version: '3.8'

services:
    java-tron-node:
        container_name: java-tron-node
        image: tronprotocol/java-tron
        restart: always
        networks:
            - eth-network
        volumes:
            - ./data/config:/java-tron/config
            - ./data/output-directory:/java-tron/output-directory
            - ./data/logs:/java-tron/logs
        ports:
            - 8090:8090
            - 18888:18888
            - 5555:5555
        command: "-c /java-tron/config/main_net_config.conf --es"
```

``` conf
# main_net_config.conf
node {
    ......
    openHistoryQueryWhenLiteFN = true
    ......
}

event.subscribe = {
    native = {
        useNativeQueue = true
        bindport = 5555
        sendqueuelength = 1000
    }

    topics = [
        {
          triggerName = "block"
          enable = ture
          topic = "block"
          solidified = false
        },
        ......
    ]
}
```

``` node
// zeromq.js
var zmq = require("zeromq");
var sock = zmq.socket("sub");

sock.connect("tcp://127.0.0.1:5555");
// sock.subscribe("*");
// sock.subscribe("blockTrigger");
sock.subscribe("block");
console.log("Subscriber connected to port 5555");

sock.on("message", function(topic, message) {
    console.log(
        "received a message related to:",
        Buffer.from(topic).toString(),
        ", containing message:",
        Buffer.from(message).toString()
    );
});

```
response ``` Subscriber connected to port 5555 ``` 
No other messages
Thanks!
