### ISSUE TITLE
Best practices for optimizing full node performance

### ISSUE THREAD

**Issue by breezytm** [tronprotocol/java-tron#6160]
Hello,

I’m an RPC provider setting up a full node using Docker, but I’ve been experiencing an issue where the http port stops responding, eventually timing out. I reached out on Discord but haven’t received any help. Could you provide best practices for configuring the node for optimal performance? Any recommendations would be greatly appreciated.

`docker-compose.yml`

```
version: '3.8'

services:
  java-tron:
    image: tronprotocol/java-tron
    container_name: java-tron
    restart: unless-stopped
    ports:
      - "8535:8535" # Json RPC Port
      - "8090:8090" # API Port
      - "50051:50051" # GRPC Port
      - "18888:18888" # P2P Port
    volumes:
      - ./config:/java-tron/conf # Configuration files
      - ./data:/java-tron/data # Blockchain data
      - ./logs:/java-tron/logs # log files
    environment:
      - JAVA_OPTS=-Xmx20g -Xms20g
    command: [
      "-c", "/java-tron/conf/config.conf",
      "-d", "/java-tron/data",
      "-w"
    ]
```

I followed the recommendation from this [issue](https://github.com/tronprotocol/java-tron/issues/5305) as well as increasing the `-JAVA_OPTS` from `Xmx10g -Xms10g` to `Xmx20g -Xms20g` which has improved the timeout

```
  http = [
    #  {
    #    component = "GetNowBlockServlet",
    #    strategy = "GlobalPreemptibleAdapter",
    #    paramString = "permit=1"
    #  },

    #  {
    #    component = "GetAccountServlet",
    #    strategy = "IPQPSRateLimiterAdapter",
    #    paramString = "qps=1"
    #  },

    #  {
    #    component = "ListWitnessesServlet",
    #    strategy = "QpsRateLimiterAdapter",
    #    paramString = "qps=1"
    #  }
       {
         component = "JsonRpcServlet",
         strategy = "QpsRateLimiterAdapter",
         paramString = "qps=20000"
       },
       {
         component = "JsonRpcServlet",
         strategy = "IPQPSRateLimiterAdapter",
         paramString = "qps=20000"
       }   
  ],
```
